### ISSUE TITLE
How to extend a Collection

### ISSUE THREAD

**Issue by neurosnap** [CenterForOpenScience/modular-odm#86]
How would I go about adding functionality at the collection level using modular-odm?

For example, if I would like to map reduce a collection:

http://api.mongodb.org/python/2.0/api/pymongo/collection.html#pymongo.collection.Collection.map_reduce

**Comment by lyndsysimon** [comment]
To my knowledge there is nothing on `StoredObject` that is specific to any backend - and as far as I know, that's by design at this point.

You might consider either subclassing it to something like `MongoStoredObject`, or we'll need to settle on an architecture through which collection-level methods can be exposed in a backend-independent way. Would you be interested in helping define what that might look like?
